### ISSUE TITLE
rough_piet: Rust logo example panics

### ISSUE THREAD

**Issue by flxzt** [orhanbalci/rough-rs#1]
Hey, thank you for creating this amazing crate / port! I hope to use it in my app soon.

One thing that I noticed while trying out the examples: The rust logo example panics currently:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /mnt/Daten/source/clones/rough-rs/roughr/src/renderer.rs:991:46
```

Backtrace:
```
   3: core::option::Option<T>::unwrap
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/option.rs:775:21
   4: roughr::renderer::pattern_fill_polygons
             at /mnt/Daten/source/clones/rough-rs/roughr/src/renderer.rs:991:24
   5: roughr::generator::Generator::path
             at /mnt/Daten/source/clones/rough-rs/roughr/src/generator.rs:319:32
   6: rough_piet::kurbo_generator::KurboGenerator::path
             at ./src/kurbo_generator.rs:292:24
   7: rust_logo::main
             at ./examples/rust_logo.rs:30:34
```

**Comment by orhanbalci** [comment]
Should be fixed with https://github.com/orhanbalci/rough-rs/commit/15b3548b62e9fdb36905df47b76de697f7274b30

**Comment by flxzt** [comment]
Thanks! I wonder if it would be better to fall back instead of panicking if the fill style is not provided by the builder. If I am reading it right, rough.js [falls back to hachure](https://github.com/rough-stuff/rough/blob/9bb9d4d927a74bae305e27e8b5be270ddcfbbe7c/src/fillers/filler.ts#L13)

**Comment by orhanbalci** [comment]
Let me check it and I'll fix that.

**Comment by orhanbalci** [comment]
This commit defaults to hachure if no style is given https://github.com/orhanbalci/rough-rs/commit/33da6ee9d50034cbe833e48767c0439dfff1c70d
