### ISSUE TITLE
Codebase depends on nightly

### ISSUE THREAD

**Issue by flxzt** [orhanbalci/rough-rs#17]
Hi, I have been trying to build the library again for upcoming piet dependency bumps/a new release and noticed that the `iter_map_windows` stdlib feature is required, which currently is nightly only.

Is it possible to revert to stable-only code, or gate uses of nightly dependent code behind a `nightly` feature?

**Comment by orhanbalci** [comment]
I'll try to refactor to stable-code only.

**Comment by orhanbalci** [comment]
error comes from a new crate i was working on. It was incomplete.  removed that crate from workspace.

**Comment by flxzt** [comment]
thanks!
