### ISSUE TITLE
add generator methods for quadratic and cubic bezier curves with control points

### ISSUE THREAD

**Issue by flxzt** [orhanbalci/rough-rs#4]
I don't know how closely you want to follow rough.js because it does not have the API that I am suggesting, but I think it would be useful if there were additional generator methods that generate bezier curves by supplying start, end and the control points. Currently it is only possible to generate a spline that goes through the given points, but it is not possible to create single curves with the control points yourself.

What I am suggesting (roughly):

```rust
impl Generator {

...

pub fn bezier_quadratic<F: Trig + Float + FromPrimitive + MulAssign + Display>(
        &self,
        start: Point2D<F>,
        cp: Point2D<F>,
        end: Point2D<F>,
    ) -> KurboDrawable<F> {
        todo!()
    }

pub fn bezier_cubic<F: Trig + Float + FromPrimitive + MulAssign + Display>(
        &self,
        start: Point2D<F>,
        cp1: Point2D<F>,
        cp2: Point2D<F>,
        end: Point2D<F>,
    ) -> KurboDrawable<F> {
        todo!()
    }
}

...

```

**Comment by orhanbalci** [comment]
I would like to preserve functionality from rough.js but we are not limited to that only. We can definitely add this sort of useful functions to the crate.

**Comment by flxzt** [comment]
Okay, nice! I am working on it, I'll submit a PR soon
