### ISSUE TITLE
Curve fill does not match the stroke curve

### ISSUE THREAD

**Issue by flxzt** [orhanbalci/rough-rs#5]
There seems to be a bug with how the fill area for curves is calculated. It does not match the stroke curve.  My guess from looking at it is that the fill area uses some of the specified points of the curve as control points, while the stroke curve uses them as spline points.

This only seems to happen when the curve has 3 points .

![curve](https://user-images.githubusercontent.com/19841886/204051110-f59300f2-a1a5-4591-8cd2-b79c94298d5b.png)

The code that generated this image:

```rust
const WIDTH: usize = 500;
const HEIGHT: usize = 300;
/// For now, assume pixel density (dots per inch)
const DPI: f32 = 96.;

/// Feature "png" needed for save_to_file() and it's disabled by default for optional dependencies
/// cargo run --example mondrian --features png
fn main() {
    let mut device = Device::new().unwrap();
    let mut bitmap = device.bitmap_target(WIDTH, HEIGHT, 1.0).unwrap();
    let mut rc = bitmap.render_context();
    let options = OptionsBuilder::default()
        .stroke(Srgb::from_raw(&[114u8, 87u8, 82u8]).into_format())
        .fill(Srgb::from_raw(&[254u8, 246u8, 201u8]).into_format())
        .fill_style(FillStyle::Hachure)
        .fill_weight(DPI * 0.01)
        .build()
        .unwrap();
    let generator = KurboGenerator::new(options);
    let points = [
        Point2D::new(0.0, HEIGHT as f32 / 2.0),
        Point2D::new((1.0 / 3.0 ) * WIDTH as f32 , HEIGHT as f32),
        Point2D::new(WIDTH as f32 , 0.0),
    ];
    let curve = generator.curve::<f32>(&points);
    let background_color = Color::from_hex_str("96C0B7").unwrap();

    rc.fill(
        Rect::new(0.0, 0.0, WIDTH as f64, HEIGHT as f64),
        &background_color,
    );
    curve.draw(&mut rc);
    rc.finish().unwrap();
    std::mem::drop(rc);

    bitmap.save_to_file("curve.png").expect("file save error");
}

```

**Comment by orhanbalci** [comment]
I think rough.js has the same bug here. When a 3 points curve passed to curve_to_bezier function it just appends last point and returns [4 points](https://github.com/pshihn/bezier-points/blob/master/src/curve-to-bezier.ts#L13-L19) But as you said these points are now interpreted as bezier control points which in result shrinks the fill area to a smaller one. I fixed this problem by reevaluating resulting 4 points. https://github.com/orhanbalci/rough-rs/commit/3d47f29920568fd41438d6c1740adf57e62460b4

**Comment by flxzt** [comment]
Can confirm, this is no longer happening.
