### ISSUE TITLE
Refactor colors to support transparency

### ISSUE THREAD

**Issue by flxzt** [orhanbalci/rough-rs#8]
as already mentioned in #7, it would be nice to have colors that support transparency, especially for solid fills.

**Comment by orhanbalci** [comment]
This commit adds support for alpha channel for stoke and fill colors. https://github.com/orhanbalci/rough-rs/commit/94b496d32a9b422d7299f99dba2604e83a216366

**Comment by flxzt** [comment]
Thank you for implementing it!

**Comment by orhanbalci** [comment]
👍
